### ISSUE TITLE
Installing Blender Add-In

### ISSUE THREAD

**Issue by ChgoChad** [ahmsville/Ahmsville-Dial-App#2]
I followed the instructions to install the Blender Add-In and ran into issues installing the two dependencies using PIP.  When I ran those two lines in the command prompt, the modules installed, however they went to my global Python cache (in my `AppData` folder) rather than the local cache for the Python that is included with Blender, and because of this Blender was not able to activate the add-in claiming those modules were not installed.   

I solved the issue by changing the command line slightly, telling it to ignore the global environment.  Here are the command lines that worked for me:
- `cd C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin`  (in my case I'm using Blender 3.0)
- `python.exe -E -s -I -m ensurepip`  (in my case pip was already installed)
- `python.exe -E -s -I -m pip install pywin32`
- `python.exe -E -s -I -m pip install pynput`

Just thought I'd share what worked for me in case anyone else finds it useful.

**Comment by ahmsville** [comment]
Hi Chad,

Thank you for sharing this. I have not upgraded my blender yet (still on 2.93), I'll be referring to your tip when I do.
